# Generated by Django 4.0.1 on 2022-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel')),
                ('account_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='account_type')),
                ('chat', models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_id')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
