# Generated by Django 4.0.1 on 2022-01-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seller_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='seller_id'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='customer_id'),
        ),
    ]
