# Generated by Django 4.0.1 on 2022-01-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('discussion_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='discussion_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
