# Generated by Django 4.0 on 2021-12-29 08:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=users.models.nameFile, verbose_name='image'),
        ),
    ]
