# Generated by Django 4.0 on 2022-01-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, verbose_name='descriptions'),
        ),
    ]
