# Generated by Django 4.0.1 on 2022-01-31 07:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image1',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=users.models.nameFile, verbose_name='image1'),
        ),
    ]
