# Generated by Django 4.0.1 on 2022-06-05 10:35

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_document',
            field=models.ImageField(default='uploads/users_placeholder.png', upload_to=users.models.nameFile, verbose_name='image_document'),
        ),
    ]
