# Generated by Django 4.0 on 2022-01-10 10:34

import announcement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='uploads/announcement.png', upload_to=announcement.models.nameFile, verbose_name='image'),
        ),
    ]
