# Generated by Django 4.0 on 2021-12-28 12:05

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='event_name')),
                ('event_start_date', models.DateField(blank=True, null=True, verbose_name='event_start_date')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='event_end_date')),
                ('venue', models.CharField(blank=True, max_length=255, null=True, verbose_name='venue')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions')),
                ('image', models.ImageField(default='uploads/events_placeholder.png', upload_to=events.models.nameFile, verbose_name='image')),
            ],
        ),
    ]
