# Generated by Django 4.0.1 on 2022-01-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='no_going',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no_going'),
        ),
        migrations.AddField(
            model_name='events',
            name='no_interested',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no_interested'),
        ),
    ]
