# Generated by Django 4.0.1 on 2022-01-31 02:39

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_options_alter_events_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image1',
            field=models.ImageField(default='uploads/events_placeholder.png', upload_to=events.models.nameFile, verbose_name='image1'),
        ),
    ]
