# Generated by Django 4.0 on 2021-12-27 01:10

import discussionspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussionspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions')),
                ('image', models.ImageField(default='uploads/Discussionspace_placeholder.png', upload_to=discussionspace.models.nameFile, verbose_name='image')),
            ],
        ),
    ]
