# Generated by Django 4.0 on 2022-01-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussionspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionspace',
            options={'ordering': ['-id']},
        ),
    ]
