# Generated by Django 4.0.1 on 2022-01-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussionspace', '0002_alter_discussionspace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionspace',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
    ]
