# Generated by Django 4.0 on 2021-12-26 22:32

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='category')),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, verbose_name='price')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='descriptions')),
                ('broker_id', models.CharField(blank=True, max_length=255, verbose_name='broker_id')),
                ('image', models.ImageField(default='uploads/marketplace_placeholder.png', upload_to=marketplace.models.nameFile, verbose_name='image')),
            ],
        ),
    ]
