# Generated by Django 4.0 on 2021-12-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_marketplace_broker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_email'),
        ),
    ]
